### ISSUE TITLE
Take OAuth control away from me

### ISSUE THREAD

**Issue by TJTorola** [appacademy/app-academy-chrome-tab#30]
Hey all, I still have control over the OAuth setup for this chrome tab, and as much as I like limitless power I think it would be better to transfer this to an account controlled by App Academy. It's used so that users can authenticate their accounts and see the daily curriculum. There is also a AWS Lambda function involved to obscure the private key for the OAuth. Once someone decides to take on this burden we can work it out in here to transfer the token and lambda over. Thanks.

**Comment by TJTorola** [comment]
Bump @composerinteralia

**Comment by composerinteralia** [comment]
I no longer work at App Academy, but perhaps @tduek could help

**Comment by kevinbmccall14** [comment]
Hey @TJTorola, I am a current App Academy Engineer. Am I correct in that all we need to do is change the the lambdaUrl in the settings.js file after we move your Lambda Function over to an App Academy AWS account?

**Comment by TJTorola** [comment]
@kevinbmccall14 Hey, yeah so you need to change that, and also make a OAuth app on github at https://github.com/settings/developers and use the public/private keys in both the Lambda and the same settings.js file.

**Comment by TJTorola** [comment]
@kevinbmccall14 OK, well, I couldn't actually find that when I was trying to do the transfer. It looks like it needs to be a github user. But I actually just put in a request to transfer it over to the `appacademy` organization. Any org admins should be able to accept it. I think github sent out an email confirm.

**Comment by TJTorola** [comment]
Appears to be done now, awesome!
